In [4]:
# 3rd party imports
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Local imports
sys.path.append("../")
from utils.logs import make_logger
from data_processing import TransportationDataProcessor

# Set up logging
logger = make_logger(include_stdout=True, log_prefix="test")

# Set up the processor
processor = TransportationDataProcessor(logger=logger)

# Run the preprocessing steps
processor.preprocess_data()

print("Static data:\n", processor.static_data.head())
print("Dynamic data:\n", processor.dynamic_data.head())

# Construct the GNN data
gnn_data = processor.prepare_gnn_data()
for split, graphs in gnn_data.items():
    if graphs:
        print(f"{split}: {len(graphs)} graphs")
        print(
            f"  Sample graph - Nodes: {graphs[0].x.shape[0]}, "
            f"Features: {graphs[0].x.shape[1]}, "
            f"Edges: {graphs[0].edge_index.shape[1]}"
        )

/Users/robstallman/projects/transportation-models/scripts/data_processing.py:231: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.2 0.2 1.  0.  0.4]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  self.static_data.loc[:, static_features_to_scale.columns] = (
/Users/robstallman/projects/transportation-models/scripts/data_processing.py:231: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.         0.66666667 0.16666667 1.         0.        ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  self.static_data.loc[:, static_features_to_scale.columns] = (
/Users/robstallman/projects/transportation-models/scripts/data_processing.py:231: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.68181818 1.         0.         0.31818182 0.04545455]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  self.static_data.loc[:, static_features_to_scale.columns] = (

Static data:
   link_id from_node_id to_node_id Station ID    Abs PM    Length  \
0     0.0          0.0        1.0        0.0  0.044352  1.000000
1     1.0          1.0        2.0        1.0  1.000000  0.829787
2     2.0          2.0        3.0        2.0  0.686576  0.031915
3     3.0          3.0        4.0        3.0  0.813128  0.000000
4     4.0          4.0        5.0        4.0  0.000000  0.000000

   free_flow_speed  congestion_wave_speed  jam_density
0              0.2               0.000000     0.681818
1              0.2               0.666667     1.000000
2              1.0               0.166667     0.000000
3              0.0               1.000000     0.318182
4              0.4               0.000000     0.045455
Dynamic data:
             timestamp Station ID  pct_observed  normalized_flow_[vphpl]  \
0 2022-01-01 00:00:00        0.0      0.683318                 0.151394
1 2022-01-01 00:05:00        0.0      0.173247                 0.164675
2 2022-01-01 00:10:00        0.0      0.207836                 0.151394
3 2022-01-01 00:15:00        0.0      0.842392                 0.162019
4 2022-01-01 00:20:00        0.0      0.326475                 0.156707

   normalized_density_[vpmpl]
0                    0.210101
1                    0.229814
2                    0.198663
3                    0.156912
4                    0.184998
train: 1411 graphs
  Sample graph - Nodes: 5, Features: 7, Edges: 4
val: 301 graphs
  Sample graph - Nodes: 5, Features: 7, Edges: 4
test: 302 graphs
  Sample graph - Nodes: 5, Features: 7, Edges: 4

In [117]:
processor.static_data

,link_id,from_node_id,to_node_id,Station ID,Abs PM,Length,free_flow_speed,congestion_wave_speed,jam_density
0,0.0,0.0,1.0,0.0,0.044352,1.000000,0.2,0.000000,0.681818
1,1.0,1.0,2.0,1.0,1.000000,0.829787,0.2,0.666667,1.000000
2,2.0,2.0,3.0,2.0,0.686576,0.031915,1.0,0.166667,0.000000
3,3.0,3.0,4.0,3.0,0.813128,0.000000,0.0,1.000000,0.318182
4,4.0,4.0,5.0,4.0,0.000000,0.000000,0.4,0.000000,0.045455

In [118]:
processor.dynamic_data

,timestamp,Station ID,pct_observed,normalized_flow_[vphpl],normalized_density_[vpmpl]
0,2022-01-01 00:00:00,0.0,0.683318,0.151394,0.210101
1,2022-01-01 00:05:00,0.0,0.173247,0.164675,0.229814
2,2022-01-01 00:10:00,0.0,0.207836,0.151394,0.198663
3,2022-01-01 00:15:00,0.0,0.842392,0.162019,0.156912
4,2022-01-01 00:20:00,0.0,0.326475,0.156707,0.184998
...,...,...,...,...,...
10075,2022-01-07 23:35:00,4.0,0.864393,0.083898,0.107117
10076,2022-01-07 23:40:00,4.0,0.685537,0.080085,0.103500
10077,2022-01-07 23:45:00,4.0,0.759967,0.088983,0.120783
10078,2022-01-07 23:50:00,4.0,0.563372,0.062288,0.138341
10079,2022-01-07 23:55:00,4.0,0.699986,0.081356,0.124745

In [114]:
from torch_geometric.loader import DataLoader as GNNDataLoader
batch_size = 32
gnn_train_loader = GNNDataLoader(gnn_data["train"], batch_size=batch_size, shuffle=True, drop_last=True)
gnn_val_loader = GNNDataLoader(gnn_data['val'], batch_size=batch_size, shuffle=False)
gnn_test_loader = GNNDataLoader(gnn_data['test'], batch_size=batch_size, shuffle=False)

for batch in gnn_train_loader:
    print(batch)
    print(batch.num_graphs)

DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32
DataBatch(x=[160, 7], edge_index=[2, 128], edge_attr=[128, 1], y=[160], timestamp=[32], batch=[160], ptr=[33])
32

In [111]:
# Get the first graph object
data = gnn_data['train'][0]

print(data)
print('===========================================================================================================')

# Gather some statistics about the graph.
print(f'Number of nodes: {data.num_nodes}')
print(f'Number of edges: {data.num_edges}')
print(f'Average node degree: {data.num_edges / data.num_nodes:.2f}')
print(f'Has isolated nodes: {data.has_isolated_nodes()}')
print(f'Has self-loops: {data.has_self_loops()}')
print(f'Is undirected: {data.is_undirected()}')

Data(x=[5, 7], edge_index=[2, 4], edge_attr=[4, 1], y=[5], timestamp=2022-01-01 00:00:00)
===========================================================================================================
Number of nodes: 5
Number of edges: 4
Average node degree: 0.80
Has isolated nodes: False
Has self-loops: False
Is undirected: False

In [90]:
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

class GCN(torch.nn.Module):
    def __init__(self, num_features: int, num_targets: int, num_hidden_layers: int = 16):
        super().__init__()
        self.conv1 = GCNConv(num_features, num_hidden_layers)
        self.conv2 = GCNConv(num_hidden_layers, num_targets)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index

        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        x = F.log_softmax(x, dim=1)

        return x.mean(dim=1)

In [116]:
device = torch.device('cpu')
model = GCN(num_features=7, num_targets=160).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)

def train_loop(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)

    for batch, data in enumerate(dataloader):
        # Compute prediction and loss
        pred = model(data)
        loss = loss_fn(pred, data.y)

        # Backpropagation
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        if batch % 10 == 0:
            loss, current = loss.item(), batch * batch_size + len(data.x)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

def test_loop(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, correct = 0, 0

    with torch.no_grad():
        for data in dataloader:
            pred = model(data)
            test_loss += loss_fn(pred, data.y).item()
            correct += (pred.argmax(1) == data.y).type(torch.float).sum().item()

    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")
         
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)
epochs = 100
for t in range(epochs):
    print(f"Epoch {t+1}\n----------------------------------------")
    train_loop(gnn_train_loader, model, loss_fn, optimizer)

Epoch 1
----------------------------------------
loss: 26.953003  [  160/ 1411]
loss: 26.936865  [  480/ 1411]
loss: 26.942245  [  800/ 1411]
loss: 26.964581  [ 1120/ 1411]
loss: 26.930243  [ 1440/ 1411]
Epoch 2
----------------------------------------
loss: 26.924999  [  160/ 1411]
loss: 26.939758  [  480/ 1411]
loss: 26.934280  [  800/ 1411]
loss: 26.942596  [ 1120/ 1411]
loss: 26.960016  [ 1440/ 1411]
Epoch 3
----------------------------------------
loss: 26.947052  [  160/ 1411]
loss: 26.960598  [  480/ 1411]
loss: 26.945972  [  800/ 1411]
loss: 26.938391  [ 1120/ 1411]
loss: 26.959635  [ 1440/ 1411]
Epoch 4
----------------------------------------
loss: 26.920689  [  160/ 1411]
loss: 26.946198  [  480/ 1411]
loss: 26.926189  [  800/ 1411]
loss: 26.954128  [ 1120/ 1411]
loss: 26.952753  [ 1440/ 1411]
Epoch 5
----------------------------------------
loss: 26.958765  [  160/ 1411]
loss: 26.948044  [  480/ 1411]
loss: 26.930573  [  800/ 1411]
loss: 26.966801  [ 1120/ 1411]
loss: 26.958715  [ 1440/ 1411]
Epoch 6
----------------------------------------
loss: 26.926640  [  160/ 1411]
loss: 26.954229  [  480/ 1411]
loss: 26.937271  [  800/ 1411]
loss: 26.950949  [ 1120/ 1411]
loss: 26.930538  [ 1440/ 1411]
Epoch 7
----------------------------------------
loss: 26.927277  [  160/ 1411]
loss: 26.941626  [  480/ 1411]
loss: 26.925690  [  800/ 1411]
loss: 26.934673  [ 1120/ 1411]
loss: 26.935064  [ 1440/ 1411]
Epoch 8
----------------------------------------
loss: 26.934311  [  160/ 1411]
loss: 26.942194  [  480/ 1411]
loss: 26.930676  [  800/ 1411]
loss: 26.943043  [ 1120/ 1411]
loss: 26.943207  [ 1440/ 1411]
Epoch 9
----------------------------------------
loss: 26.951004  [  160/ 1411]
loss: 26.923788  [  480/ 1411]
loss: 26.948740  [  800/ 1411]
loss: 26.938641  [ 1120/ 1411]
loss: 26.958563  [ 1440/ 1411]
Epoch 10
----------------------------------------
loss: 26.938843  [  160/ 1411]
loss: 26.942480  [  480/ 1411]
loss: 26.940649  [  800/ 1411]
loss: 26.945057  [ 1120/ 1411]
loss: 26.936518  [ 1440/ 1411]
Epoch 11
----------------------------------------
loss: 26.962536  [  160/ 1411]
loss: 26.948080  [  480/ 1411]
loss: 26.932583  [  800/ 1411]
loss: 26.957952  [ 1120/ 1411]
loss: 26.941523  [ 1440/ 1411]
Epoch 12
----------------------------------------
loss: 26.933649  [  160/ 1411]
loss: 26.950916  [  480/ 1411]
loss: 26.942327  [  800/ 1411]
loss: 26.962820  [ 1120/ 1411]
loss: 26.953411  [ 1440/ 1411]
Epoch 13
----------------------------------------
loss: 26.945007  [  160/ 1411]
loss: 26.943689  [  480/ 1411]
loss: 26.934921  [  800/ 1411]
loss: 26.927652  [ 1120/ 1411]
loss: 26.938110  [ 1440/ 1411]
Epoch 14
----------------------------------------
loss: 26.938747  [  160/ 1411]
loss: 26.945456  [  480/ 1411]
loss: 26.960230  [  800/ 1411]
loss: 26.943201  [ 1120/ 1411]
loss: 26.942438  [ 1440/ 1411]
Epoch 15
----------------------------------------
loss: 26.961914  [  160/ 1411]
loss: 26.939112  [  480/ 1411]
loss: 26.942104  [  800/ 1411]
loss: 26.955952  [ 1120/ 1411]
loss: 26.948597  [ 1440/ 1411]
Epoch 16
----------------------------------------
loss: 26.938934  [  160/ 1411]
loss: 26.958187  [  480/ 1411]
loss: 26.927307  [  800/ 1411]
loss: 26.968130  [ 1120/ 1411]
loss: 26.956980  [ 1440/ 1411]
Epoch 17
----------------------------------------
loss: 26.941181  [  160/ 1411]
loss: 26.930470  [  480/ 1411]
loss: 26.948523  [  800/ 1411]
loss: 26.939093  [ 1120/ 1411]
loss: 26.940784  [ 1440/ 1411]
Epoch 18
----------------------------------------
loss: 26.942638  [  160/ 1411]
loss: 26.951700  [  480/ 1411]
loss: 26.932154  [  800/ 1411]
loss: 26.935852  [ 1120/ 1411]
loss: 26.956945  [ 1440/ 1411]
Epoch 19
----------------------------------------
loss: 26.935419  [  160/ 1411]
loss: 26.935949  [  480/ 1411]
loss: 26.951199  [  800/ 1411]
loss: 26.939045  [ 1120/ 1411]
loss: 26.950207  [ 1440/ 1411]
Epoch 20
----------------------------------------
loss: 26.960983  [  160/ 1411]
loss: 26.941690  [  480/ 1411]
loss: 26.949884  [  800/ 1411]
loss: 26.923223  [ 1120/ 1411]
loss: 26.940037  [ 1440/ 1411]
Epoch 21
----------------------------------------
loss: 26.982441  [  160/ 1411]
loss: 26.953491  [  480/ 1411]
loss: 26.955235  [  800/ 1411]
loss: 26.944025  [ 1120/ 1411]
loss: 26.951365  [ 1440/ 1411]
Epoch 22
----------------------------------------
loss: 26.959797  [  160/ 1411]
loss: 26.936590  [  480/ 1411]
loss: 26.952734  [  800/ 1411]
loss: 26.961264  [ 1120/ 1411]
loss: 26.954523  [ 1440/ 1411]
Epoch 23
----------------------------------------
loss: 26.956244  [  160/ 1411]
loss: 26.945673  [  480/ 1411]
loss: 26.925335  [  800/ 1411]
loss: 26.932465  [ 1120/ 1411]
loss: 26.943226  [ 1440/ 1411]
Epoch 24
----------------------------------------
loss: 26.937860  [  160/ 1411]
loss: 26.943441  [  480/ 1411]
loss: 26.946051  [  800/ 1411]
loss: 26.924854  [ 1120/ 1411]
loss: 26.941223  [ 1440/ 1411]
Epoch 25
----------------------------------------
loss: 26.936163  [  160/ 1411]
loss: 26.915371  [  480/ 1411]
loss: 26.927221  [  800/ 1411]
loss: 26.945751  [ 1120/ 1411]
loss: 26.964529  [ 1440/ 1411]
Epoch 26
----------------------------------------
loss: 26.931757  [  160/ 1411]
loss: 26.925671  [  480/ 1411]
loss: 26.922665  [  800/ 1411]
loss: 26.944645  [ 1120/ 1411]
loss: 26.948063  [ 1440/ 1411]
Epoch 27
----------------------------------------
loss: 26.939768  [  160/ 1411]
loss: 26.932486  [  480/ 1411]
loss: 26.930033  [  800/ 1411]
loss: 26.959400  [ 1120/ 1411]
loss: 26.955921  [ 1440/ 1411]
Epoch 28
----------------------------------------
loss: 26.954693  [  160/ 1411]
loss: 26.931240  [  480/ 1411]
loss: 26.933435  [  800/ 1411]
loss: 26.939693  [ 1120/ 1411]
loss: 26.934307  [ 1440/ 1411]
Epoch 29
----------------------------------------
loss: 26.936462  [  160/ 1411]
loss: 26.956524  [  480/ 1411]
loss: 26.955481  [  800/ 1411]
loss: 26.956562  [ 1120/ 1411]
loss: 26.930384  [ 1440/ 1411]
Epoch 30
----------------------------------------
loss: 26.944052  [  160/ 1411]
loss: 26.943974  [  480/ 1411]
loss: 26.917530  [  800/ 1411]
loss: 26.935261  [ 1120/ 1411]
loss: 26.960165  [ 1440/ 1411]
Epoch 31
----------------------------------------
loss: 26.941320  [  160/ 1411]
loss: 26.962168  [  480/ 1411]
loss: 26.956558  [  800/ 1411]
loss: 26.940943  [ 1120/ 1411]
loss: 26.944891  [ 1440/ 1411]
Epoch 32
----------------------------------------
loss: 26.951960  [  160/ 1411]
loss: 26.935736  [  480/ 1411]
loss: 26.954014  [  800/ 1411]
loss: 26.958698  [ 1120/ 1411]
loss: 26.947983  [ 1440/ 1411]
Epoch 33
----------------------------------------
loss: 26.951880  [  160/ 1411]
loss: 26.943354  [  480/ 1411]
loss: 26.954981  [  800/ 1411]
loss: 26.928547  [ 1120/ 1411]
loss: 26.937567  [ 1440/ 1411]
Epoch 34
----------------------------------------
loss: 26.952961  [  160/ 1411]
loss: 26.933804  [  480/ 1411]
loss: 26.932684  [  800/ 1411]
loss: 26.938580  [ 1120/ 1411]
loss: 26.947702  [ 1440/ 1411]
Epoch 35
----------------------------------------
loss: 26.937643  [  160/ 1411]
loss: 26.945028  [  480/ 1411]
loss: 26.963919  [  800/ 1411]
loss: 26.953217  [ 1120/ 1411]
loss: 26.936350  [ 1440/ 1411]
Epoch 36
----------------------------------------
loss: 26.944012  [  160/ 1411]
loss: 26.966827  [  480/ 1411]
loss: 26.957544  [  800/ 1411]
loss: 26.928427  [ 1120/ 1411]
loss: 26.932846  [ 1440/ 1411]
Epoch 37
----------------------------------------
loss: 26.928082  [  160/ 1411]
loss: 26.953289  [  480/ 1411]
loss: 26.959875  [  800/ 1411]
loss: 26.953815  [ 1120/ 1411]
loss: 26.948853  [ 1440/ 1411]
Epoch 38
----------------------------------------
loss: 26.950216  [  160/ 1411]
loss: 26.934483  [  480/ 1411]
loss: 26.956442  [  800/ 1411]
loss: 26.943302  [ 1120/ 1411]
loss: 26.935375  [ 1440/ 1411]
Epoch 39
----------------------------------------
loss: 26.942236  [  160/ 1411]
loss: 26.943527  [  480/ 1411]
loss: 26.938293  [  800/ 1411]
loss: 26.941586  [ 1120/ 1411]
loss: 26.936270  [ 1440/ 1411]
Epoch 40
----------------------------------------
loss: 26.924459  [  160/ 1411]
loss: 26.914566  [  480/ 1411]
loss: 26.938086  [  800/ 1411]
loss: 26.947992  [ 1120/ 1411]
loss: 26.945227  [ 1440/ 1411]
Epoch 41
----------------------------------------
loss: 26.960321  [  160/ 1411]
loss: 26.955387  [  480/ 1411]
loss: 26.933041  [  800/ 1411]
loss: 26.942041  [ 1120/ 1411]
loss: 26.945400  [ 1440/ 1411]
Epoch 42
----------------------------------------
loss: 26.955517  [  160/ 1411]
loss: 26.958551  [  480/ 1411]
loss: 26.958210  [  800/ 1411]
loss: 26.924927  [ 1120/ 1411]
loss: 26.940491  [ 1440/ 1411]
Epoch 43
----------------------------------------
loss: 26.928310  [  160/ 1411]
loss: 26.924082  [  480/ 1411]
loss: 26.953806  [  800/ 1411]
loss: 26.945658  [ 1120/ 1411]
loss: 26.928974  [ 1440/ 1411]
Epoch 44
----------------------------------------
loss: 26.954136  [  160/ 1411]
loss: 26.948547  [  480/ 1411]
loss: 26.933014  [  800/ 1411]
loss: 26.924067  [ 1120/ 1411]
loss: 26.934826  [ 1440/ 1411]
Epoch 45
----------------------------------------
loss: 26.946741  [  160/ 1411]
loss: 26.941105  [  480/ 1411]
loss: 26.946735  [  800/ 1411]
loss: 26.935730  [ 1120/ 1411]
loss: 26.968039  [ 1440/ 1411]
Epoch 46
----------------------------------------
loss: 26.931812  [  160/ 1411]
loss: 26.942825  [  480/ 1411]
loss: 26.952229  [  800/ 1411]
loss: 26.937916  [ 1120/ 1411]
loss: 26.924433  [ 1440/ 1411]
Epoch 47
----------------------------------------
loss: 26.947174  [  160/ 1411]
loss: 26.946198  [  480/ 1411]
loss: 26.949121  [  800/ 1411]
loss: 26.971203  [ 1120/ 1411]
loss: 26.940256  [ 1440/ 1411]
Epoch 48
----------------------------------------
loss: 26.951395  [  160/ 1411]
loss: 26.935162  [  480/ 1411]
loss: 26.965702  [  800/ 1411]
loss: 26.938807  [ 1120/ 1411]
loss: 26.962778  [ 1440/ 1411]
Epoch 49
----------------------------------------
loss: 26.929058  [  160/ 1411]
loss: 26.943029  [  480/ 1411]
loss: 26.957520  [  800/ 1411]
loss: 26.941761  [ 1120/ 1411]
loss: 26.939798  [ 1440/ 1411]
Epoch 50
----------------------------------------
loss: 26.941187  [  160/ 1411]
loss: 26.918848  [  480/ 1411]
loss: 26.929743  [  800/ 1411]
loss: 26.939877  [ 1120/ 1411]
loss: 26.940027  [ 1440/ 1411]
Epoch 51
----------------------------------------
loss: 26.942642  [  160/ 1411]
loss: 26.958612  [  480/ 1411]
loss: 26.950323  [  800/ 1411]
loss: 26.934637  [ 1120/ 1411]
loss: 26.929501  [ 1440/ 1411]
Epoch 52
----------------------------------------
loss: 26.941839  [  160/ 1411]
loss: 26.946003  [  480/ 1411]
loss: 26.939514  [  800/ 1411]
loss: 26.933598  [ 1120/ 1411]
loss: 26.936747  [ 1440/ 1411]
Epoch 53
----------------------------------------
loss: 26.945072  [  160/ 1411]
loss: 26.946039  [  480/ 1411]
loss: 26.927135  [  800/ 1411]
loss: 26.934427  [ 1120/ 1411]
loss: 26.946945  [ 1440/ 1411]
Epoch 54
----------------------------------------
loss: 26.937719  [  160/ 1411]
loss: 26.949047  [  480/ 1411]
loss: 26.950897  [  800/ 1411]
loss: 26.957346  [ 1120/ 1411]
loss: 26.944754  [ 1440/ 1411]
Epoch 55
----------------------------------------
loss: 26.954632  [  160/ 1411]
loss: 26.943375  [  480/ 1411]
loss: 26.937439  [  800/ 1411]
loss: 26.935638  [ 1120/ 1411]
loss: 26.957392  [ 1440/ 1411]
Epoch 56
----------------------------------------
loss: 26.953201  [  160/ 1411]
loss: 26.919994  [  480/ 1411]
loss: 26.961187  [  800/ 1411]
loss: 26.950642  [ 1120/ 1411]
loss: 26.931751  [ 1440/ 1411]
Epoch 57
----------------------------------------
loss: 26.952229  [  160/ 1411]
loss: 26.945227  [  480/ 1411]
loss: 26.958704  [  800/ 1411]
loss: 26.965363  [ 1120/ 1411]
loss: 26.938602  [ 1440/ 1411]
Epoch 58
----------------------------------------
loss: 26.933167  [  160/ 1411]
loss: 26.932007  [  480/ 1411]
loss: 26.955471  [  800/ 1411]
loss: 26.940628  [ 1120/ 1411]
loss: 26.950031  [ 1440/ 1411]
Epoch 59
----------------------------------------
loss: 26.950434  [  160/ 1411]
loss: 26.948254  [  480/ 1411]
loss: 26.941467  [  800/ 1411]
loss: 26.940731  [ 1120/ 1411]
loss: 26.940632  [ 1440/ 1411]
Epoch 60
----------------------------------------
loss: 26.935745  [  160/ 1411]
loss: 26.941462  [  480/ 1411]
loss: 26.949167  [  800/ 1411]
loss: 26.945095  [ 1120/ 1411]
loss: 26.957287  [ 1440/ 1411]
Epoch 61
----------------------------------------
loss: 26.944794  [  160/ 1411]
loss: 26.956024  [  480/ 1411]
loss: 26.960255  [  800/ 1411]
loss: 26.960932  [ 1120/ 1411]
loss: 26.944199  [ 1440/ 1411]
Epoch 62
----------------------------------------
loss: 26.913092  [  160/ 1411]
loss: 26.936817  [  480/ 1411]
loss: 26.935284  [  800/ 1411]
loss: 26.963160  [ 1120/ 1411]
loss: 26.932196  [ 1440/ 1411]
Epoch 63
----------------------------------------
loss: 26.927685  [  160/ 1411]
loss: 26.945160  [  480/ 1411]
loss: 26.941900  [  800/ 1411]
loss: 26.961407  [ 1120/ 1411]
loss: 26.933527  [ 1440/ 1411]
Epoch 64
----------------------------------------
loss: 26.917889  [  160/ 1411]
loss: 26.950550  [  480/ 1411]
loss: 26.950836  [  800/ 1411]
loss: 26.932110  [ 1120/ 1411]
loss: 26.943201  [ 1440/ 1411]
Epoch 65
----------------------------------------
loss: 26.939337  [  160/ 1411]
loss: 26.964727  [  480/ 1411]
loss: 26.957066  [  800/ 1411]
loss: 26.927185  [ 1120/ 1411]
loss: 26.924921  [ 1440/ 1411]
Epoch 66
----------------------------------------
loss: 26.948004  [  160/ 1411]
loss: 26.944687  [  480/ 1411]
loss: 26.952230  [  800/ 1411]
loss: 26.949158  [ 1120/ 1411]
loss: 26.942169  [ 1440/ 1411]
Epoch 67
----------------------------------------
loss: 26.936350  [  160/ 1411]
loss: 26.939243  [  480/ 1411]
loss: 26.918238  [  800/ 1411]
loss: 26.924892  [ 1120/ 1411]
loss: 26.933777  [ 1440/ 1411]
Epoch 68
----------------------------------------
loss: 26.942377  [  160/ 1411]
loss: 26.944738  [  480/ 1411]
loss: 26.939825  [  800/ 1411]
loss: 26.966206  [ 1120/ 1411]
loss: 26.958298  [ 1440/ 1411]
Epoch 69
----------------------------------------
loss: 26.946814  [  160/ 1411]
loss: 26.943716  [  480/ 1411]
loss: 26.927826  [  800/ 1411]
loss: 26.947241  [ 1120/ 1411]
loss: 26.934574  [ 1440/ 1411]
Epoch 70
----------------------------------------
loss: 26.937262  [  160/ 1411]
loss: 26.953699  [  480/ 1411]
loss: 26.925781  [  800/ 1411]
loss: 26.935944  [ 1120/ 1411]
loss: 26.946239  [ 1440/ 1411]
Epoch 71
----------------------------------------
loss: 26.932318  [  160/ 1411]
loss: 26.965893  [  480/ 1411]
loss: 26.949926  [  800/ 1411]
loss: 26.928778  [ 1120/ 1411]
loss: 26.917614  [ 1440/ 1411]
Epoch 72
----------------------------------------
loss: 26.927917  [  160/ 1411]
loss: 26.931650  [  480/ 1411]
loss: 26.950888  [  800/ 1411]
loss: 26.957621  [ 1120/ 1411]
loss: 26.949902  [ 1440/ 1411]
Epoch 73
----------------------------------------
loss: 26.956757  [  160/ 1411]
loss: 26.944098  [  480/ 1411]
loss: 26.934393  [  800/ 1411]
loss: 26.913601  [ 1120/ 1411]
loss: 26.938971  [ 1440/ 1411]
Epoch 74
----------------------------------------
loss: 26.952753  [  160/ 1411]
loss: 26.928431  [  480/ 1411]
loss: 26.930561  [  800/ 1411]
loss: 26.946095  [ 1120/ 1411]
loss: 26.944620  [ 1440/ 1411]
Epoch 75
----------------------------------------
loss: 26.948147  [  160/ 1411]
loss: 26.936646  [  480/ 1411]
loss: 26.924702  [  800/ 1411]
loss: 26.955133  [ 1120/ 1411]
loss: 26.944736  [ 1440/ 1411]
Epoch 76
----------------------------------------
loss: 26.957037  [  160/ 1411]
loss: 26.941305  [  480/ 1411]
loss: 26.934149  [  800/ 1411]
loss: 26.953686  [ 1120/ 1411]
loss: 26.924084  [ 1440/ 1411]
Epoch 77
----------------------------------------
loss: 26.937372  [  160/ 1411]
loss: 26.948303  [  480/ 1411]
loss: 26.931833  [  800/ 1411]
loss: 26.948511  [ 1120/ 1411]
loss: 26.939922  [ 1440/ 1411]
Epoch 78
----------------------------------------
loss: 26.945423  [  160/ 1411]
loss: 26.942911  [  480/ 1411]
loss: 26.938696  [  800/ 1411]
loss: 26.945526  [ 1120/ 1411]
loss: 26.923269  [ 1440/ 1411]
Epoch 79
----------------------------------------
loss: 26.931385  [  160/ 1411]
loss: 26.929678  [  480/ 1411]
loss: 26.957825  [  800/ 1411]
loss: 26.949896  [ 1120/ 1411]
loss: 26.928247  [ 1440/ 1411]
Epoch 80
----------------------------------------
loss: 26.930851  [  160/ 1411]
loss: 26.922968  [  480/ 1411]
loss: 26.959167  [  800/ 1411]
loss: 26.952499  [ 1120/ 1411]
loss: 26.948984  [ 1440/ 1411]
Epoch 81
----------------------------------------
loss: 26.922281  [  160/ 1411]
loss: 26.949896  [  480/ 1411]
loss: 26.959568  [  800/ 1411]
loss: 26.940958  [ 1120/ 1411]
loss: 26.940643  [ 1440/ 1411]
Epoch 82
----------------------------------------
loss: 26.939011  [  160/ 1411]
loss: 26.920521  [  480/ 1411]
loss: 26.945847  [  800/ 1411]
loss: 26.932987  [ 1120/ 1411]
loss: 26.941425  [ 1440/ 1411]
Epoch 83
----------------------------------------
loss: 26.946543  [  160/ 1411]
loss: 26.956539  [  480/ 1411]
loss: 26.946667  [  800/ 1411]
loss: 26.947577  [ 1120/ 1411]
loss: 26.946060  [ 1440/ 1411]
Epoch 84
----------------------------------------
loss: 26.944162  [  160/ 1411]
loss: 26.919819  [  480/ 1411]
loss: 26.955557  [  800/ 1411]
loss: 26.945032  [ 1120/ 1411]
loss: 26.942331  [ 1440/ 1411]
Epoch 85
----------------------------------------
loss: 26.941101  [  160/ 1411]
loss: 26.942026  [  480/ 1411]
loss: 26.955265  [  800/ 1411]
loss: 26.933170  [ 1120/ 1411]
loss: 26.945679  [ 1440/ 1411]
Epoch 86
----------------------------------------
loss: 26.955841  [  160/ 1411]
loss: 26.938366  [  480/ 1411]
loss: 26.935711  [  800/ 1411]
loss: 26.928293  [ 1120/ 1411]
loss: 26.941751  [ 1440/ 1411]
Epoch 87
----------------------------------------
loss: 26.950354  [  160/ 1411]
loss: 26.942440  [  480/ 1411]
loss: 26.955990  [  800/ 1411]
loss: 26.957571  [ 1120/ 1411]
loss: 26.960449  [ 1440/ 1411]
Epoch 88
----------------------------------------
loss: 26.933411  [  160/ 1411]
loss: 26.954544  [  480/ 1411]
loss: 26.924189  [  800/ 1411]
loss: 26.943478  [ 1120/ 1411]
loss: 26.942974  [ 1440/ 1411]
Epoch 89
----------------------------------------
loss: 26.953070  [  160/ 1411]
loss: 26.940876  [  480/ 1411]
loss: 26.937189  [  800/ 1411]
loss: 26.954687  [ 1120/ 1411]
loss: 26.928177  [ 1440/ 1411]
Epoch 90
----------------------------------------
loss: 26.946930  [  160/ 1411]
loss: 26.942663  [  480/ 1411]
loss: 26.934101  [  800/ 1411]
loss: 26.937450  [ 1120/ 1411]
loss: 26.949055  [ 1440/ 1411]
Epoch 91
----------------------------------------
loss: 26.947617  [  160/ 1411]
loss: 26.940685  [  480/ 1411]
loss: 26.936401  [  800/ 1411]
loss: 26.937622  [ 1120/ 1411]
loss: 26.965576  [ 1440/ 1411]
Epoch 92
----------------------------------------
loss: 26.947021  [  160/ 1411]
loss: 26.953516  [  480/ 1411]
loss: 26.928553  [  800/ 1411]
loss: 26.942577  [ 1120/ 1411]
loss: 26.935608  [ 1440/ 1411]
Epoch 93
----------------------------------------
loss: 26.940708  [  160/ 1411]
loss: 26.956659  [  480/ 1411]
loss: 26.923504  [  800/ 1411]
loss: 26.937613  [ 1120/ 1411]
loss: 26.955898  [ 1440/ 1411]
Epoch 94
----------------------------------------
loss: 26.946238  [  160/ 1411]
loss: 26.926525  [  480/ 1411]
loss: 26.958094  [  800/ 1411]
loss: 26.964045  [ 1120/ 1411]
loss: 26.939137  [ 1440/ 1411]
Epoch 95
----------------------------------------
loss: 26.949345  [  160/ 1411]
loss: 26.935968  [  480/ 1411]
loss: 26.956699  [  800/ 1411]
loss: 26.943695  [ 1120/ 1411]
loss: 26.927582  [ 1440/ 1411]
Epoch 96
----------------------------------------
loss: 26.949463  [  160/ 1411]
loss: 26.913822  [  480/ 1411]
loss: 26.956295  [  800/ 1411]
loss: 26.912561  [ 1120/ 1411]
loss: 26.926733  [ 1440/ 1411]
Epoch 97
----------------------------------------
loss: 26.943043  [  160/ 1411]
loss: 26.945332  [  480/ 1411]
loss: 26.931065  [  800/ 1411]
loss: 26.951160  [ 1120/ 1411]
loss: 26.939560  [ 1440/ 1411]
Epoch 98
----------------------------------------
loss: 26.953711  [  160/ 1411]
loss: 26.948605  [  480/ 1411]